### ISSUE TITLE
code building problem

### ISSUE THREAD

**Issue by AlphaMTV** [suhaasr/15769_final_project#1]
Hi, Suhaasr

We try to compile the codes and find some problems with the Halide part.
We want to know what version of Halide used in the compilation of your codes,
so we can download the correct one.

Could you kindly provide the info?

Thank you

**Comment by suhaasr** [comment]
Hi AlphaMTV, 

Unfortunately I don't have the exact version number because I deleted my local files from the university file system. However, I built Halide from the latest official halide commit at the halide-lang website around 9 months ago,  so you could probably find a commit from around that time and build it. Here's a set of instructions I compiled for my classmates to help them build the version I used. I hope this helps! 

These instructions assume you are building in /tmp and then moving the resulting binary as needed

1. Download the latest Unix/Linux Source from https://cmake.org/download/ and extract it in /tmp

2. cd CMAKE_DIR

3. cmake .

4. make

5. Install llvm3.8 in /tmp using the instructions from http://graphics.cs.cmu.edu/courses/15769/fall2016/article/2 , but when using cmake, instead use CMAKE_DIR/bin/cmake instead (the version of cmake installed on the clusters is out of date)

6. git clone https://github.com/halide/Halide in /tmp
[you would need to revert this to a stable commit approximately 9 months ago] 

7. setenv LLVM_CONFIG /tmp/llvm3.8/build/bin/llvm-config

8. setenv CLANG /tmp/llvm3.8/build/bin/clang

9. cd /tmp/Halide

10. make

11. Copy /tmp/Halide/bin to wherever you need it
